src/scripts/http-info.coffee
This fixes a crash on http-info.coffee as many web pages don't have this meta tag.
=> Don't assume that webpages have meta tags with descriptions.

README.md
It was pointing to the old (deprecated) `github/hubot-scripts` repo.
=> Fix URL for "hubot-scripts organisation" link

src/scripts/shipit.coffee
Am a huge fan of the 'ship it' images but the one that seems out of place is the ship flooding the street.  Suggest removing it to keep the humor consistent and reliable.  
For that matter, might be worth just shifting to only squirrels by removing:
* http://images.cheezburger.com/completestore/2011/11/2/aa83c0c4-2123-4bd3-8097-966c9461b30c.jpg
* http://i.imgur.com/DPVM1.png
=> removing actual ship image

src/scripts/bitbucket.coffee
The URL for the bitbucket instructions on creating a POST service led to a 404. I fixed the link to point to the correct page.
=> Fixed URL to bitbucket POST service instructions

src/scripts/eardropping.coffee
We wanted to be able to trigger multiple events in a sequence with eardropping but the existing implementation would trigger events in an almost random order. Added an order parameter to the task object and set up a bit to sort tasks that match the current eardrop trigger. I'm quite new to coffeescript and hubot programming so there's probably some room to refactor my additions.
The ordering still isn't 100% accurate. Hubot will trigger the tasks in the correct sequence but target actions may appear to the user out of order. For example, when hubot hears "kaboom" it should trigger "how many days since kaboom?", then echo <url to a gif> and finally reset the days since kaboom counter to 0. On the server side, this executes in the desired order but on client side, those messages might be …
=> Added support for multiple actions

src/scripts/jenkins.coffee
Currently if you request a non-existent project be built (normally due to a typo) it spews large quantities of ugly HTML into the channel.  This commit makes it handle 404s with a 1 line response instead.
=> Handle 404 errors

src/scripts/pagerduty.coffee
- Change erroneous `resolve` example to `ack`
- Nitpick capitalisation
=> Update PagerDuty script documentation

src/scripts/chess.coffee
The previous script only allowed one game to be run per bot. This simply stores the chess games in a store relative to the channel name, allowing multiple games to be run at one time.
=> Allowed Chess to be channel/room independant

src/scripts/github-merge.coffee
I don't know how the original github-merge.coffee script is assumed to be used,
but to make Hubot merge pull requests on GitHub, I needed this change.
This fix changes the regex used from:
http://rubular.com/r/GYTfo8swxd
To:
http://rubular.com/r/ajwxmrfDZ4
=> Fix github-merge to work against messages like `hubot merge github_user/repository/myfix into base`

src/scripts/gosling.coffee
- Added case insensitivity to the regex
- Updated the api route used to calculate total posts
=> Fix gosling to return goslings!

src/scripts/hangout.coffee
I wanted to have 3 copies of this script that would each answer to `hangout`, `hangout2` and `hangout3`.
Problem was the current regex is not specific enough and was matching on all three.
This change tightens up the regex match to be more specific to allow people to run multiple copies.
after this PR I can then copy `node_modules/hubot-scripts/src/scripts/hangout.coffee` to `scripts/hangout2.coffee` and `scripts/hangout3.coffee` and modify the ENV_VARS accordingly.
=> [hangout.coffee] tighten up regex to only match hangout and not hangout2 etc

src/scripts/reddit.coffee
=> remove htmlparser dependency

src/scripts/clark.coffee
See also: https://github.com/github/hubot-scripts/issues/1255
=> Fix require statement for clark

src/scripts/factoid.coffee
Title says it all. Will aim to split this script out per #1113 if I work on it.
=> factoids shouldn't be case-sensitive

src/scripts/github-commits.coffee
Added optional HUBOT_GITHUB_COMMITS_ONLY env variable that will restrict messages to pushes with commits and filter out the creation/deletion of tags and branches. Handy if you have an automated build system creating a lot of tags.
Also, conditionally add base_ref to message if it is specified. It can be undefined.
=> github-commits: Add ability to filter out tag/branch creation messages

src/scripts/ive.coffee
"Experience" comes up too often outside of context of "user experience". 
"Does anyone have any experience with XXX tool" is annoying rather than fun. What do you think?
=> Remove experience as a trigger word - ive.coffee

src/scripts/eardropping.coffee
The "multiple actions" feature added to the ear dropping script broke its original functionality. This PR fixes things. Multiple actions will only be stored if multiple actions are provided by the user.
=> Fix ear dropping script

src/scripts/foass.coffee
I've found that the FOAAS responds when I'm not expecting it to, when Hubot hears any word beginning with 'fu' like fun, future, etc. E.g. hearing
fun time at the bar last night, eh?
… would get a FOAAS response. I think the regex needs improving.
This patch alters it to listen for 'fu' either followed by nothing, or followed by -space- and something (which can now be any number of words, whereas previously it was just a single word).
=> Improve robot hear regex of foaas

package.json
The only thing this includes is https://github.com/github/hubot-scripts/pull/1696 which starts to collect data about scripts that have package replacements.
=> Release 2.17.0

replacements.json
Mentioned in https://github.com/github/hubot-scripts/issues/1641#issuecomment-218440541 but several things don't have a .coffee in them, so aren't detected as a replacement.
=> Make sure to include .coffee for everything
