github/hubot-scripts

src/scripts/encourage.coffee
I know this repo is deprecated, and this is a small and subtle thing but since it shows up in the hubot help a user noticed.
=> Encourage proper spelling

src/scripts/applause.coffee
Adding the word boundaries prevents accidental image displays.
=> Added word boundaries in the applause.coffee

src/scripts/cheer.coffee
Now uses the imgur API and shares the same env variable used by gif-me.coffee to keep things clean.
=> Fixing cheer.coffee

src/scripts/remind.coffee
- Adds support for "hubot remind me on \<date/time\> to \<action\>"
- Requires new npm packages:
- moment, for duration/time formatting
- lodash, for utility functions
- chrono-node, for parsing natural language type dates (e.g. next Tuesday, Tomorrow at 3:00pm, etc.)
- Adds "hubot delete reminder <action>" command
- Adds "hubot show reminders" command
- Fixes some bugs
=> Add features and fix some bugs in remind.coffee

src/scripts/dribbble.coffee
given the current regexp, match[4] is undefined.
=> fix query match index

src/scripts/availability.coffee
This update makes the "i am" optional so that a user can just say 'hubot busy' or 'hubot free'.  It also adds additional statuses.
=> Availability Script Updates

package.json
vim fail on updating the version in https://github.com/github/hubot-scripts/pull/1642
=> Version bump to 2.16.0

src/scripts/9gag.coffee
Deprecate 9gag in favor of https://github.com/luijose/hubot-9gag
/cc @luijose https://github.com/github/hubot-scripts/issues/1641
=> Deprecate 9gag script

src/scripts/jenkins.coffee
Hello,
After using this script myself, I thought I'd thank you by adding this. I found that while running tests or having had tests aborted, it was confusing that were only PASS or FAIL outcomes. Hopefully this is useful to others!
Thanks
=> Adding specificity to job statuses

src/scripts/cleverbot.coffee
This is a very simple change to address the issue in cleverbot-node that was recently fixed:
https://github.com/fojas/cleverbot-node/issues/11
I realize this repo is deprecated, but I figured that it wasn't worth a separate repository or npm module.
=> fix for cleverbot 0.2.1

src/scripts/celery-man.coffee
Looked lame in chats. Now fixed.
=> Oyster was not a gif

src/scripts/applause.coffee
=> Removed broken gif

src/scripts/meme_captain.coffee
Memecaptain.com recently deprecated their old API causing this script to no longer work. Updated script to use new API with polling logic.
Also added a few common/popular meme images.
=> updated to use new memecaptain API

package.json
includes:
* https://github.com/github/hubot-scripts/pull/1650
* https://github.com/github/hubot-scripts/pull/1652
* https://github.com/github/hubot-scripts/pull/1655
* https://github.com/github/hubot-scripts/pull/1659
* https://github.com/github/hubot-scripts/pull/1658
* https://github.com/github/hubot-scripts/pull/1657
* https://github.com/github/hubot-scripts/pull/1656
* https://github.com/github/hubot-scripts/pull/1654
* https://github.com/github/hubot-scripts/pull/1649
=> Release 2.16.2

src/scripts/rabbitmq.coffee
This would allow the rabbitmq script to use https where as before was hardcoded for http.
=> added scheme as an option for rabbitmq.coffee

src/scripts/jira.coffee
Hi,
I am new to hubot and coffeescript and ran into some difficultly figuring out why the REST API was failing. Turns out that I had used 'http' instead of 'https' and the JIRA API call was returning 301 instead of 200. The code as written isn't checking for this and assumes a 200 and was passing the 301 message body (which is HTML) to the cb JSON.parse(body), which then gacked trying to parse it since it wasn't JSON.
I put 3 error checks:
1. if the httprequest err fails outright
2. only call JSON.parse(body) if the REST all returns 200
3. non 200 returns log the status code and body to console to aid debugging.
Thanks,
George
=> jira.coffee: add error checking around API call

package.json, replacements.json
I added one last replacement in https://github.com/github/hubot-scripts/pull/1697  and forgot to validate JSON 😓  That's fixed. I'd say we should have CI and pre-release checks, but if this is dying, I'm not sure it's worth it.
=> Hotfix 2.17.1

replacements.json
https://github.com/fordnox/hubot-coin seems to be a direct replacement.
=> Add replacement for coin.coffee

package.json
Includes some updates to replacements.json:
* add coin.coffee to the list https://github.com/github/hubot-scripts/issues/1699
* fix entries that didn't have .coffee in them: https://github.com/github/hubot-scripts/issues/1700
=> Release 2.17.2

replacements.json
Forked from work done by @willdurand on https://github.com/TailorDev/hubot
https://github.com/bdashrad/hubot-bang-bang
https://www.npmjs.com/package/hubot-bang-bang
=> added replacement for bangbang.coffee
